[package]
name = "apollo"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
window-vibrancy = { version = "0.4" }
serde_json = "1"
rdev = "0.3"
raw-window-handle = "0.5.2"


[dependencies.tauri]
version = "1"
features = [ "system-tray",
    "global-shortcut-all",
    "global-shortcut",
    "window-show",
    "window-hide",
    "window-set-position",
    "shell-open",
]

[dependencies.windows]
version = "0.58.0"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Media",
    "Win32_Media_Audio",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_WindowsProgramming",
    "Win32_System_ProcessStatus",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_CompositionSwapchain",
    "Win32_Graphics_Dwm",
    "Win32_UI_Controls",
]

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
