[package]
name = "mix-monkey"
version = "0.2.15"
description = "Desktop Audio Manager"
authors = ["Zach Connelly"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "^1.5.3", features = [] }

[dependencies]
serde = "^1.0.204"
serde_yaml = "0.9.34"
windows-volume-control = { git = "https://github.com/zmconnelly/windows-volume-control.git" }
serialport = "4.0"
inputbot = "0.6"
log = "0.4"
flexi_logger = "0.29.0"

[dependencies.tauri]
version = "^1.7.1"
features = [
    "system-tray",
    "global-shortcut-all",
    "global-shortcut",
    "window-show",
    "window-hide",
    "window-set-position",
    "shell-open",
]

[dependencies.windows]
version = "^0.58.0"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Media",
    "Win32_Media_Audio",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
    "Win32_System_WindowsProgramming",
    "Win32_System_ProcessStatus",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_CompositionSwapchain",
    "Win32_Graphics_Dwm",
    "Win32_UI_Controls",
    "Win32_Media_Audio_Endpoints",
]

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
