
# Mapping of audio sessions to encoders
# Master is a reserved session name for system volume control
# Other is a reserved session name for all active processes not otherwise listed
sessions:
- name: "master"
  encoder: 0
- name: "chrome"
  encoder: 1
- name: "discord"
  encoder: 2
- name: "other"
  encoder: 3

# Volume mixer (system tray) configs
mixer:
  hotkey: "CommandOrControl+Shift+V"

# Arduino connection configs
arduino:
  com_port: COM3
  baud_rate: 9600
