---
arduino:
  enabled: true
  com_port: COM3
  baud_rate: 9600
sessions:
  - name: master
    keybinds: ~
  - name: chrome
    keybinds: ~
  - name: discord
    keybinds: ~
  - name: other
    keybinds: ~
mixer:
  enabled: true
  hotkey: LCtrl + LShift + M
system:
  autostart: true
  show_console: true