---
arduino:
  enabled: false
  com_port: COM3
  baud_rate: 9600
sessions:
  - name: master
    encoder: 0
    keybinds: ~
  - name: chrome
    encoder: 1
    keybinds: ~
  - name: discord
    encoder: 2
    keybinds: ~
  - name: other
    encoder: 3
    keybinds: ~
mixer:
  hotkey: Ctrl+Shift+M