name: Build and Release App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"
          bun --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Tauri CLI and dependencies
        run: |
          bun install
          bun add -g @tauri-apps/cli

      - name: Build Tauri app
        run: bun run tauri build

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tauri App (${{ matrix.platform }})
          path: src-tauri/target/release/bundle/nsis/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: build_artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build_artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
