name: Build and Release App

on:
  push:
    tags:
      - "v*.*.*" # Triggers the workflow on version tag pushes (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install Tauri CLI and dependencies
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload Release Artifact
        if: startsWith(matrix.platform, 'windows') || startsWith(matrix.platform, 'ubuntu') || startsWith(matrix.platform, 'macos')
        uses: actions/upload-artifact@v3
        with:
          name: Tauri App (${{ matrix.platform }})
          path: src-tauri/target/release/bundle/nsis/*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: build_artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build_artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
