name: Build and Release App

on:
  push:
    branches:
      - releases
    # tags:
    #   - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> src-tauri/target"

      - run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ #  __VERSION__ replaced with app version.
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

      # - name: Upload Release Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Tauri App (${{ matrix.platform }})
      #     path: src-tauri/target/release/bundle/nsis/*.exe

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/')

  #   steps:
  #     - name: Download Build Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: build_artifacts

  #     - name: Create GitHub Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         files: build_artifacts/**/*
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
