name: Build and Release App

on:
  push:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "src-tauri -> target"

      - run: bun install
      - run: bun tauri build

      - name: Build Release
        id: build_release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          files: |
            src-tauri/target/release/bundle/nsis/*.exe
            config.yaml
            arduino/sketch/sketch.ino
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
